export const DUMMY_BOOKS = [
  {
    id: 'b1',
    title: '1984',
    writerId: '1',
    imageUrl: '1984.jpg',
    genre: 'Distopia',
    summary: 'Uma sociedade totalitária e vigilância constante. Winston Smith tenta se rebelar contra o controle do Partido e do Grande Irmão.',
  },
  {
    id: 'b2',
    title: 'A Revolução dos Bichos',
    writerId: '1',
    imageUrl: 'a_revolucao_dos_bichos.jpg',
    genre: 'Distopia',
    summary: 'Uma sátira política onde os animais de uma fazenda se rebelam contra os humanos, mas a utopia se transforma em uma tirania ainda pior.',
  },
  {
    id: 'b3',
    title: 'O Iluminado',
    writerId: '2',
    imageUrl: 'o_iluminado.jpg',
    genre: 'Terror',
    summary: 'Jack Torrance, um escritor com problemas, aceita ser o zelador de um hotel isolado durante o inverno, onde forças sobrenaturais o levam à loucura.',
  },
  {
    id: 'b4',
    title: 'It',
    writerId: '2',
    imageUrl: 'it.jpg',
    genre: 'Terror',
    summary: 'Um grupo de crianças enfrenta uma entidade maligna que se alimenta do medo e assume a forma de um palhaço chamado Pennywise. Anos depois, eles precisam retornar para acabar com a ameaça.',
  },
  {
    id: 'b5',
    title: 'O Senhor dos Anéis: A Sociedade do Anel',
    writerId: '3',
    imageUrl: 'sociedade_do_anel.jpg',
    genre: 'Fantasia',
    summary: 'Frodo Bolseiro herda um anel mágico e perigoso. Ele deve embarcar em uma jornada épica para destruí-lo e salvar a Terra Média do Senhor do Escuro Sauron.',
  },
  {
    id: 'b6',
    title: 'O Hobbit',
    writerId: '3',
    imageUrl: 'o_hobbit.jpg',
    genre: 'Fantasia',
    summary: 'Bilbo Bolseiro é um hobbit pacato que se junta a um grupo de anões e a um mago para recuperar o tesouro de um dragão, embarcando em uma aventura inesperada.',
  },
  {
    id: 'b7',
    title: 'Código Limpo',
    writerId: '4',
    imageUrl: 'codigo_limpo.jpg',
    genre: 'Engenharia de Software',
    summary: 'Um guia prático com princípios, padrões e práticas para escrever código de alta qualidade, legível e de fácil manutenção.',
  },
  {
    id: 'b9',
    title: 'Eu, Robô',
    writerId: '5',
    imageUrl: 'eu_robo.jpg',
    genre: 'Ciência Ficção',
    summary: 'Uma coletânea de contos interligados sobre robôs, explorando as Três Leis da Robótica e as complexas interações entre humanos e máquinas.',
  },
  {
    id: 'b10',
    title: 'Fundação',
    writerId: '5',
    imageUrl: 'fundacao.jpg',
    genre: 'Ciência Ficção',
    summary: 'Hari Seldon, um matemático que pode prever o futuro, cria a Fundação para preservar o conhecimento e reduzir o tempo de uma era de trevas iminente.',
  },
  {
    id: 'b11',
    title: 'Jogador Nº 1',
    writerId: '6',
    imageUrl: 'jogador_n1.jpg',
    genre: 'Ficção Científica',
    summary: 'Em um futuro distópico, Wade Watts mergulha no mundo virtual do OASIS para encontrar um easter egg deixado por seu criador, que promete uma fortuna e controle total do mundo virtual.',
  }
];